### ISSUE TITLE
workshop: WM

### ISSUE THREAD

**Issue by yanivabir** [huyslab/relmed_analysis_behaviour#18]
model-free
- [x] Acc curves by appearance / set-size etc.

before pt.2 data
- [x] re-write QL models and WM alone models to allow for 3 actions
- [x] parameter recovery for all multiaction models using Pilot 6 task structure
- [x] fit Q-learner w/ 2 learning rates and WM models (??) to first run
- [x] split-half reliabilities for QL and WM models
- [ ] Correlations with questionnaires

after pt.2 data
- [x] test-retest reliability
- [x] reliability of difference in parameters
- [x] export all parameters to .csv for overall matrix

other
- [ ] correlation with QL parameters in PILT
- [x] (if time) get PPCs for Q-learner + WM models (need to account for early stopping

**Comment by qdercon** [comment]
before new data
- [ ] reliability (split-half) (use Haoyang's scatterplot code)
-[ ] fit Q-learner w/ 2 learning rates and WM to first run
- [ ] (if time) get PPCs for Q-learner + WM models (need to account for early stopping

after new data
- [ ] test-retest reliability
- [ ] export all parameters to .csv for overall matrix
