### ISSUE TITLE
Task correlations for each presentation

### ISSUE THREAD

**Issue by yanivabir** [huyslab/relmed_analysis_behaviour#39]
- [ ] Vigour
- [ ] PIT
- [ ] WM
- [ ] Generalization
- [ ] Reversal

**Comment by hy-lu** [comment]
Between-task and task-questionnaire correlation matrices can be found in Questionnaires.qmd f6c40b0bbfe372de33a61e7f942875d31b946692
Hopefully, Quentin H will give some comments on this; meanwhile, we are not planning to include this in each presentation, therefore I'm closing this issue.
